using CarRent.Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace CarRent.Infrastructure
{
    public static class DataPrePopulation
    {
        private static readonly string[] FirstNames = { "Alice", "Bob", "Charlie", "Dave", "Eve", "Frank", "Grace", "Heidi", "Ivan", "Jack", "Karen", "Larry", "Megan", "Nancy", "Oliver", "Peter", "Quincy", "Rachel", "Samantha", "Trevor", "Ursula", "Victoria", "Walter", "Xavier", "Yvonne", "Zach" };
        private static readonly string[] LastNames = { "Adams", "Brown", "Carter", "Davis", "Edwards", "Franklin", "Garcia", "Hernandez", "Ishikawa", "Johnson", "Klein", "Lee", "Martin", "Nguyen", "O'Connor", "Patel", "Quinn", "Rivera", "Singh", "Thompson", "Ueda", "Valdez", "Williams", "Xiao", "Yamamoto", "Zhang" };
        private static readonly Random Random = new Random();

        private static string GenerateName()
        {
            string firstName = FirstNames[Random.Next(FirstNames.Length)];
            string lastName = LastNames[Random.Next(LastNames.Length)];
            return $"{firstName} {lastName}";
        }

        public static void UseDataPrePopulation(this IApplicationBuilder app)
        {
            using var serciveScope = app.ApplicationServices.CreateScope();
            SeedData(serciveScope.ServiceProvider.GetService<ApplicationDbContext>());
        }

        private static void SeedData(ApplicationDbContext context)
        {
            if (!context.Set<Car>().Any())
            {
                context.Set<Car>().AddRange(
                    new Car
                    {
                        CurrentLocation = new Location { 
                            City ="Napoli",
                            Country = "Italy",
                            Latitude = 40.847261979137436,
                            Longitude = 14.312058323004266
                        },
                        Name = "Dacia Logan MCV",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/dacia/logan_mcv_lrg.jpg",
                        Type = CarType.Estate,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 3,
                        SmallBag = 2,
                        MileageLimit =0, 
                        PricePerDay =50,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.888928234509,
                            Longitude = 14.309043494843904,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Citroen C3",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/citroen/c3_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 45,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.919851840520295,
                            Longitude = 14.218619483625968,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Volkswagen Polo",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/volkswagen/polo_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 70,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.902552950411554,
                            Longitude = 14.228190983116145,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Kia Picanto",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/kia/picanto_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 4,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 70,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.84374487548638,                            
                            Longitude = 14.116159666387542,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Fiat 500X",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/fiat/500x_lrg.jpg",
                        Type = CarType.Medium,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 75,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.86842099315672,
                            Longitude = 14.350070565550771,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Opel Corsa",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/opel/corsa_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 55,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.8972331571794,                            
                            Longitude = 14.273681249799491,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Ford Fiesta",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/ford/fiesta_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 80,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.88075205808668,                            
                            Longitude = 14.404487224187077,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Fiat 500L",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/fiat/500l_lrg.jpg",
                        Type = CarType.Medium,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 75,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2,GenerateName()),
                            new CarOccupiedDate(9,GenerateName()),
                            new CarOccupiedDate(12,GenerateName()),
                            new CarOccupiedDate(22,GenerateName()),
                            new CarOccupiedDate(37,GenerateName()),
                            new CarOccupiedDate(47,GenerateName()),
                            new CarOccupiedDate(63,GenerateName()),
                            new CarOccupiedDate(75,GenerateName()),
                            new CarOccupiedDate(78,GenerateName()),
                            new CarOccupiedDate(85,GenerateName()),
                            new CarOccupiedDate(91,GenerateName()),
                            new CarOccupiedDate(98,GenerateName()),
                            new CarOccupiedDate(112,GenerateName()),
                            new CarOccupiedDate(128,GenerateName()),
                            new CarOccupiedDate(132,GenerateName()),
                            new CarOccupiedDate(148,GenerateName()),
                            new CarOccupiedDate(151,GenerateName()),
                            new CarOccupiedDate(159,GenerateName()),
                            new CarOccupiedDate(163,GenerateName()),
                            new CarOccupiedDate(168,GenerateName()),
                            new CarOccupiedDate(170,GenerateName()),
                            new CarOccupiedDate(176,GenerateName()),
                            new CarOccupiedDate(182,GenerateName()),
                            new CarOccupiedDate(184,GenerateName()),
                            new CarOccupiedDate(197,GenerateName()),
                            new CarOccupiedDate(200,GenerateName()),
                            new CarOccupiedDate(201,GenerateName()),
                            new CarOccupiedDate(202,GenerateName()),
                            new CarOccupiedDate(226,GenerateName()),
                            new CarOccupiedDate(233,GenerateName()),
                            new CarOccupiedDate(251,GenerateName()),
                            new CarOccupiedDate(254,GenerateName()),
                            new CarOccupiedDate(267,GenerateName()),
                            new CarOccupiedDate(273,GenerateName()),
                            new CarOccupiedDate(277,GenerateName()),
                            new CarOccupiedDate(284,GenerateName()),
                            new CarOccupiedDate(288,GenerateName()),
                            new CarOccupiedDate(293,GenerateName()),
                            new CarOccupiedDate(295,GenerateName()),
                            new CarOccupiedDate(297,GenerateName()),
                            new CarOccupiedDate(301,GenerateName()),
                            new CarOccupiedDate(308,GenerateName()),
                            new CarOccupiedDate(309,GenerateName()),
                            new CarOccupiedDate(319,GenerateName()),
                            new CarOccupiedDate(327,GenerateName()),
                            new CarOccupiedDate(334,GenerateName()),
                            new CarOccupiedDate(335,GenerateName()),
                            new CarOccupiedDate(340,GenerateName()),
                            new CarOccupiedDate(347,GenerateName()),
                            new CarOccupiedDate(349,GenerateName())
                        }
                    }
                );
                context.SaveChanges();
            }
        }
    }
}
