using CarRent.Models;
using Core.Common.Helpers;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;

namespace CarRent.Infrastructure
{
    public static class DataPrePopulation
    {
        public static void UseDataPrePopulation(this IApplicationBuilder app)
        {
            using var serciveScope = app.ApplicationServices.CreateScope();
            SeedData(serciveScope.ServiceProvider.GetService<ApplicationDbContext>());
        }

        private static void SeedData(ApplicationDbContext context)
        {
            if (!context.Set<Car>().Any())
            {
                context.Set<Car>().AddRange(
                    new Car
                    {
                        CurrentLocation = new Location { 
                            City ="Napoli",
                            Country = "Italy",
                            Latitude = 40.847261979137436,
                            Longitude = 14.312058323004266
                        },
                        Name = "Dacia Logan MCV",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/dacia/logan_mcv_lrg.jpg",
                        Type = CarType.Estate,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 3,
                        SmallBag = 2,
                        MileageLimit =0, 
                        PricePerDay =50,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.888928234509,
                            Longitude = 14.309043494843904,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Citroen C3",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/citroen/c3_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 45,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.919851840520295,
                            Longitude = 14.218619483625968,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Volkswagen Polo",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/volkswagen/polo_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 70,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.902552950411554,
                            Longitude = 14.228190983116145,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Kia Picanto",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/kia/picanto_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 4,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 70,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.84374487548638,                            
                            Longitude = 14.116159666387542,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Fiat 500X",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/fiat/500x_lrg.jpg",
                        Type = CarType.Medium,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 75,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.86842099315672,
                            Longitude = 14.350070565550771,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Opel Corsa",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/opel/corsa_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 55,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.8972331571794,                            
                            Longitude = 14.273681249799491,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Ford Fiesta",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/ford/fiesta_lrg.jpg",
                        Type = CarType.Small,
                        Transmission = TransmissionType.Automatic,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 80,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    },
                    new Car
                    {
                        CurrentLocation = new Location
                        {
                            Latitude = 40.88075205808668,                            
                            Longitude = 14.404487224187077,
                            City = "Napoli",
                            Country = "Italy",
                        },
                        Name = "Fiat 500L",
                        ImageUrl = "https://cdn2.rcstatic.com/images/car_images/web/fiat/500l_lrg.jpg",
                        Type = CarType.Medium,
                        Transmission = TransmissionType.Manual,
                        Seats = 5,
                        LargeBag = 1,
                        SmallBag = 1,
                        MileageLimit = 0,
                        PricePerDay = 75,
                        OccupiedDates = new List<CarOccupiedDate> {
                            new CarOccupiedDate(2, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(9, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(12, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(22, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(37, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(47, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(63, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(75, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(78, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(85, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(91, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(98, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(112, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(128, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(132, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(148, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(151, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(159, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(163, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(168, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(170, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(176, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(182, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(184, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(197, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(200, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(201, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(202, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(226, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(233, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(251, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(254, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(267, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(273, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(277, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(284, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(288, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(293, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(295, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(297, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(301, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(308, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(309, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(319, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(327, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(334, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(335, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(340, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(347, GenerateRandomData.GenerateName()),
                            new CarOccupiedDate(349, GenerateRandomData.GenerateName())
                        }
                    }
                );
                context.SaveChanges();
            }
        }
    }
}
