name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/airlineapi:$GITHUB_SHA -f src/AirlineService/API/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/carrentapi:$GITHUB_SHA -f src/CarRentService/API/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/hotelapi:$GITHUB_SHA -f src/HotelService/API/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/billingapi:$GITHUB_SHA -f src/BillingService/API/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/bookingapi:$GITHUB_SHA -f src/BookingService/API/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/supportal:$GITHUB_SHA -f src/Supportal/Portal/Dockerfile .
          docker buildx build --platform linux/amd64 --push -t $DOCKERHUB_USERNAME/webportal:$GITHUB_SHA -f src/WebPortal/Portal/Dockerfile .
